### ISSUE TITLE
Composer\Script\CommandEvent deprecated

### ISSUE THREAD

**Issue by kidager** [umpirsky/PermissionsHandler#13]
While running `composer install` I got the following warning, it seems that the `Composer\Script\CommandEvent` class was replaced by `Composer\Script\Event`

``
Deprecation Notice: The callback Umpirsky\PermissionsHandler\ScriptHandler::setPermissions declared at .../vendor/umpirsky/composer-permissions-handler/src/Umpirsky/PermissionsHandler/ScriptHandler.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:289
``

**Comment by umpirsky** [comment]
@kidager Thanks for reporting this. Did you try to replace `Composer\Script\CommandEvent` with `Composer\Script\Event` and see if it works? 
PRs are welcome too. :)

**Comment by kidager** [comment]
Tested and working 👍🏻
I have submitted a PR

**Comment by umpirsky** [comment]
Merged, thanks @kidager! :+1:
