### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by darkalchemy** [umpirsky/PermissionsHandler#17]
Hey @umpirsky,

Would you be able to update this to PHP 8.0/8.1?

Many thanks for this project.

**Comment by umpirsky** [comment]
Hi!

If you submit pull request I'd gladly review and merge. Otherwise it can take some time.

**Comment by darkalchemy** [comment]
I looked at doing that yesterday but I think there was an issue with phpspec. I'll look over it again. No promises, my skills and understanding are still near beginner level.

Thank you

**Comment by darkalchemy** [comment]
Updated in #18

**Comment by darkalchemy** [comment]
Hi @umpirsky,

Could you create a new release so composer can see it?

Thanks

**Comment by umpirsky** [comment]
Done! ;)

**Comment by darkalchemy** [comment]
Thanks @umpirsky
